---

- name: Install gitenv
  command:
    # Note: using Ansible's gem module does not work for some reason.
    cmd: gem install gitenv
    creates: "{{ asdf_shims_dir }}/gitenv"
  become: true
  become_user: "{{ gitenv_user }}"
  environment:
    ASDF_RUBY_VERSION: "{{ ruby_version }}"
    PATH: "{{ asdf_shims_dir }}:{{ asdf_homebrew_dir }}/opt/asdf/bin:{{ asdf_homebrew_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"

- name: Apply gitenv
  command:
    cmd: gitenv apply
    chdir: "{{ gitenv_chdir }}"
  become: true
  become_user: "{{ gitenv_user }}"
  environment: "{{ gitenv_environment }}"
  register: result
  changed_when: false
