---

- name: Install gitenv
  gem: name=gitenv user_install=no state=latest
- name: Apply gitenv
  shell: gitenv apply chdir={{ gitenv_chdir }}
  become: yes
  become_user: "{{ gitenv_user }}"
  environment:
    GITENV_REPO: "{{ gitenv_repo }}"
    GITENV_CONFIG: "{{ gitenv_config }}"
    PATH: "{{ host_package_manager_paths }}{{ ansible_env.PATH }}"
  register: result
  changed_when: result.rc != 0
