---

- name: Install gitenv
  command:
    # Note: using Ansible's gem module does not work for some reason.
    cmd: gem install gitenv
    creates: "{{ asdf_shims_dir }}/gitenv"
  become: true
  become_user: "{{ gitenv_user }}"
  environment:
    ASDF_RUBY_VERSION: "{{ ruby_version }}"
    PATH: "{{ asdf_shims_dir }}:/usr/local/opt/asdf/bin:/usr/local/bin:{{ ansible_env.PATH }}"

- name: Apply gitenv
  command:
    cmd: gitenv apply
    chdir: "{{ gitenv_chdir }}"
  become: true
  become_user: "{{ gitenv_user }}"
  environment:
    ASDF_RUBY_VERSION: "{{ ruby_version }}"
    GITENV_REPO: "{{ gitenv_repo }}"
    GITENV_CONFIG: "{{ gitenv_config }}"
    PATH: "{{ asdf_shims_dir }}:/usr/local/bin:{{ ansible_env.PATH }}"
  register: result
  changed_when: false
